// Builds the SecAI design system:
//   src/icons.gen.ts            Lucide icon data used by <Icon>
//   dist/design-system/project  the files published to the Claude Design system artifact
//   src/tokens.css, src/fonts   tokens as CSS custom properties and font files, for the web app
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
// Packages may be hoisted to the workspace root's node_modules.
function pkgDir(name) {
  for (let dir = root; ; dir = dirname(dir)) {
    const candidate = join(dir, "node_modules", name);
    if (existsSync(candidate)) return candidate;
    if (dirname(dir) === dir) throw new Error(`Cannot find package ${name}`);
  }
}
const lucide = join(pkgDir("lucide-static"), "icons");
const out = join(root, "dist/design-system/project");

// <Icon> can draw every icon in the asset gallery (design-system/icons.json) plus these.
const EXTRA_ICONS = ["ban", "check", "chevron-right", "loader-circle", "plus"];
const COMPONENT_ICONS = [
  ...new Set([...JSON.parse(readFileSync(join(root, "design-system/icons.json"), "utf8")), ...EXTRA_ICONS]),
].sort();

function parseIcon(name) {
  const svg = readFileSync(join(lucide, `${name}.svg`), "utf8");
  const parts = [];
  for (const m of svg.matchAll(/<(path|circle|rect|line|polyline|polygon|ellipse)\s([^>]*?)\/>/g)) {
    const attrs = {};
    for (const a of m[2].matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    parts.push([m[1], attrs]);
  }
  if (!parts.length) throw new Error(`No shapes parsed from ${name}.svg`);
  return parts;
}

// 1. Icon data
const icons = Object.fromEntries(COMPONENT_ICONS.map((n) => [n, parseIcon(n)]));
writeFileSync(
  join(root, "src/icons.gen.ts"),
  `// Generated by scripts/build.mjs from lucide-static (ISC license). Do not edit.\n` +
    `export type IconName = ${COMPONENT_ICONS.map((n) => JSON.stringify(n)).join(" | ")};\n` +
    `export const ICONS: Record<IconName, Array<[string, Record<string, string>]>> = ${JSON.stringify(icons)};\n`,
);

rmSync(join(root, "dist"), { recursive: true, force: true });
mkdirSync(join(out, "components"), { recursive: true });

// 2. Bundle: one classic script assigning window.SecAI, React from window.React
const reactGlobal = {
  name: "react-global",
  setup(b) {
    b.onResolve({ filter: /^react$/ }, () => ({ path: "react", namespace: "global" }));
    b.onLoad({ filter: /.*/, namespace: "global" }, () => ({ contents: "module.exports = window.React;", loader: "js" }));
  },
};
const components = await import("node:fs").then(() =>
  [...readFileSync(join(root, "src/components.tsx"), "utf8").matchAll(/^export function (\w+)/gm)].map((m) => m[1]),
);
const result = await build({
  entryPoints: [join(root, "src/entry.ts")],
  bundle: true,
  format: "iife",
  minify: true,
  write: false,
  jsx: "transform",
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [reactGlobal],
  legalComments: "none",
  logOverride: { "module level directives cause errors when bundled": "silent" },
});
let js = result.outputFiles[0].text;
if (/<\/script|<!--/i.test(js)) throw new Error("bundle contains </script or <!--");
const header = { format: 4, namespace: "SecAI", components: components.map((name) => ({ name })) };
js = `/* @ds-bundle: ${JSON.stringify(header)} */\n/* SecAI — Copyright (C) 2026 hdbrzgr. AGPL-3.0 with an attribution term. Icons: Lucide (ISC). */\n${js}`;
writeFileSync(join(out, "components/bundle.js"), js);

// 3. Stylesheet and types
cpSync(join(root, "src/styles.css"), join(out, "components/bundle.css"));
execFileSync(process.execPath, [join(pkgDir("typescript"), "bin/tsc"),
  "--declaration", "--emitDeclarationOnly", "--strict", "--jsx", "react", "--esModuleInterop",
  "--skipLibCheck", "--target", "es2020", "--moduleResolution", "bundler", "--module", "esnext",
  "--outDir", join(root, "dist/types"), join(root, "src/components.tsx"),
]);
const dts = readFileSync(join(root, "dist/types/components.d.ts"), "utf8").replace(/^import \{ type IconName \} from "\.\/icons\.gen";\n/m, "");
const iconType = readFileSync(join(root, "src/icons.gen.ts"), "utf8").match(/export type IconName = [^;]+;/)[0];
writeFileSync(
  join(out, "components/index.d.ts"),
  `${iconType}\n${dts}\ndeclare global {\n  interface Window {\n    SecAI: {\n${components.map((c) => `      ${c}: typeof ${c};`).join("\n")}\n    };\n  }\n}\n`,
);

// 4. Authored files: README, tokens, component docs and previews, asset group READMEs
cpSync(join(root, "design-system"), out, {
  recursive: true,
  filter: (src) => !src.endsWith("icons.json"),
});

// 5. Fonts
const tokens = JSON.parse(readFileSync(join(root, "design-system/tokens.json"), "utf8"));
mkdirSync(join(out, "fonts"), { recursive: true });
for (const f of tokens.type.fonts) {
  const file = f.file.replace(/^fonts\//, "");
  const pkg = file.replace(/-latin-.*$/, "");
  cpSync(join(pkgDir(`@fontsource/${pkg}`), "files", file), join(out, "fonts", file));
}

// 6. Gallery icons to upload as assets
const gallery = JSON.parse(readFileSync(join(root, "design-system/icons.json"), "utf8"));
mkdirSync(join(root, "dist/icon-uploads"), { recursive: true });
for (const n of gallery) cpSync(join(lucide, `${n}.svg`), join(root, "dist/icon-uploads", `${n}.svg`));

// 7. tokens.css for the web app (same shape the design system page compiles)
const colorTokens = tokens.color.tokens;
const themes = tokens.color.themes.map((t) => t.id);
const val = (v, theme) => {
  const raw = typeof v === "string" ? v : (v[theme] ?? v[themes[0]]);
  const alias = /^\{(.+)\}$/.exec(raw);
  return alias ? `var(--${alias[1]})` : raw;
};
const themeBlock = (theme) =>
  colorTokens.map((t) => `  --${t.name}: ${val(t.value, theme)};`).concat(
    tokens.shadow.tokens.map((t) => `  --${t.name}: ${val(t.value, theme)};`),
  ).join("\n");
const lengths = ["spacing", "radius", "size"].flatMap((k) => tokens[k].tokens).map((t) => `  --${t.name}: ${t.value};`);
const families = Object.entries(tokens.type.families).map(([k, v]) => `  --font-${k}: ${v};`);
const faces = tokens.type.fonts.map(
  (f) => `@font-face { font-family: "${f.family}"; src: url("./fonts/${f.file.replace(/^fonts\//, "")}") format("woff2"); font-weight: ${f.weight}; font-style: ${f.style}; font-display: swap; }`,
);
const css = `/* Generated from tokens.json by scripts/build.mjs. Do not edit. */
${faces.join("\n")}
:root, [data-theme="light"] {
${themeBlock("light")}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${themeBlock("dark")}
    color-scheme: dark;
  }
}
[data-theme="dark"] {
${themeBlock("dark")}
  color-scheme: dark;
}
:root {
${lengths.concat(families).join("\n")}
}
`;
// Committed next to the components so apps import "@secai/ui/tokens.css" without a build step.
writeFileSync(join(root, "src/tokens.css"), css);
rmSync(join(root, "src/fonts"), { recursive: true, force: true });
cpSync(join(out, "fonts"), join(root, "src/fonts"), { recursive: true });

const count = (d) => readdirSync(d, { recursive: true }).length;
console.log(`Built ${components.length} components; ${count(out)} entries in dist/design-system/project`);
console.log(components.join(", "));
if (!existsSync(join(out, "README.md"))) console.warn("warning: design-system/README.md missing");
