"""scan progress, summary, attestation and finding details

Revision ID: 6e248295df6e
Revises: a28c0a7060e9
Create Date: 2026-09-25 05:39:12.754681

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e248295df6e"
down_revision: str | Sequence[str] | None = "a28c0a7060e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("findings", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("findings", sa.Column("recommendation", sa.Text(), nullable=True))
    op.add_column(
        "findings",
        sa.Column(
            "references",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            # Existing rows need a value; new rows get one from the model.
            server_default=sa.text("'[]'"),
        ),
    )
    op.add_column("scans", sa.Column("progress", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("scans", sa.Column("current_step", sa.String(length=200), nullable=True))
    op.add_column(
        "scans",
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column("scans", sa.Column("attested_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("scans", sa.Column("attested_ip", sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f("uq_targets_org_id"), "targets", ["org_id", "hostname"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_targets_org_id"), "targets", type_="unique")
    op.drop_column("scans", "attested_ip")
    op.drop_column("scans", "attested_at")
    op.drop_column("scans", "summary")
    op.drop_column("scans", "current_step")
    op.drop_column("scans", "progress")
    op.drop_column("findings", "references")
    op.drop_column("findings", "recommendation")
    op.drop_column("findings", "description")
    # ### end Alembic commands ###
